All local changes
futuro-camp/education-group-one pull request #2
Opened 2019-06-22 14:49 UTC by v-zinchenko

Dronezone final version
Safor webpage without last section and footer

2019-06-24 12:44 UTC, ghost requested changes

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
> +        <ul class="text">
Its should be a string `<h1>`, not a list

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
> +            <li><p>Safor is an intelligent personal guard platform that empowers individuals to enjoy active and safe lives, while their friends and family can enjoy peace of mind.</p></li>
Separate this one into another block.

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
> +                <li><img src="images/section5/pentagon.svg" alt="pentagon"></li>
Image and text for this image - one item. Show nesting in tags, code will be more readable. Example :
```
<li>
 <img/>
 <p></p>
</li>
```

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
>              <h2>FOR BUSINESS</h2>
Same as white block

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
>              <div class="first-row">
This block can be not separated into two different blocks. You should place all the inputs in one block and set position using flex.

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
> +        <ul class="text">
Something went wrong here. Please fix positioning. Also nesting p tag into li makes no sense. You can just put text in li item and style it as p.

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
>                  <h1>WHY SAFOR?</h1>
We have different font style in design for this title.

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
>  <body>
Looks like website is broken on resolutions 1680 and 1440

2019-06-24 12:44 UTC, muha2399 commented on safor/index.html
>                  <input type="text" class="name" placeholder="name">
On resolution 759 placeholder letters does not fit.

2019-06-25 13:12 UTC, ghost requested changes

2019-06-25 13:12 UTC, ghost commented on safor/index.html
> +            <ul class="links">
social buttons in wrong position on 1024px resolution, sizes of icons looks incorrect

2019-06-25 13:12 UTC, ghost commented on safor/index.html
> +            <input type="submit" class="submit" value="send">
Please remove bottom border on button.

2019-06-25 13:12 UTC, muha2399 commented on safor/index.html
> +        <hr>
Why there are only five lines visible instead of 7 ?

2019-06-25 13:12 UTC, muha2399 commented on safor/index.html
> +            <input type="text" class="message" placeholder="message">
As i can see, distance between placeholder and border is different on 375 resolution and less

2019-06-26 09:13 UTC, muha2399 commented on safor/index.html
> +            <input type="submit" class="submit" value="send">
Still issue

2019-06-26 09:16 UTC, ghost submitted a review, later dismissed

2019-06-29 13:33 UTC, volo-maslow approved these changes

2019-06-29 13:33 UTC, ghost approved these changes

2019-06-29 13:46 UTC, merged