init
futuro-camp/education-group-one pull request #3
Opened 2019-06-22 14:50 UTC by d-smyrnov

2019-06-24 13:47 UTC, ghost requested changes

2019-06-24 13:47 UTC, muha2399 commented on Safor/index.html
> +                <h1>SAFOR</h2>
These two h1 should be represented as one.

2019-06-24 13:47 UTC, muha2399 commented on Safor/index.html
> +                    <li>
Nesting p into li makes no sense

2019-06-24 13:47 UTC, muha2399 commented on Safor/index.html
> +    <div class="four">
replace div for each section with section tag

2019-06-24 13:47 UTC, muha2399 commented on Safor/index.html
> +            <p>Additional</p>
Margin from top item looks incorrect on 1000px resolution

2019-06-24 13:47 UTC, muha2399 commented on Safor/index.html
> +                    <a href="#"><li>How it works</li></a>
Incorrect font-size on 759px resolution

2019-06-25 13:32 UTC, ghost requested changes

2019-06-25 13:32 UTC, muha2399 commented on Safor/index.html
> +                        <p>Do not waste time to explain your location and nature of the threat, guard
On 1024px i can see text from white block, when grey is active. Please fix.

2019-06-25 13:32 UTC, muha2399 commented on Safor/index.html
> +                <input type="text" placeholder="NAME">
Distance between placeholder and bottom border should be as on mockup

2019-06-25 13:32 UTC, muha2399 commented on Safor/index.html
> +                <a href="#"><img src="img/footer/2.svg"></a>
On resolution 375, size of instagram icon incorrect. Also check distance between icons.

2019-06-25 13:32 UTC, muha2399 commented on Safor/index.html
> +                        <hr>
On resolution 320 these lines should be 1px, but now they are 2px

2019-06-26 09:05 UTC, muha2399 commented on Safor/index.html
> +                <a href="#"><img src="img/footer/2.svg"></a>
Try to use another instagram and maybe another social icons on lower resolution.

2019-06-26 09:30 UTC, ghost approved these changes

2019-06-29 13:35 UTC, ghost submitted a review, later dismissed

2019-06-29 13:38 UTC, volo-maslow requested changes

2019-06-29 13:38 UTC, volo-maslow commented on Safor/index.html
> +        <section class="topLayer">
Strange naming of the section, please use dashes or underscores to separate different words.

2019-06-29 13:38 UTC, volo-maslow commented on Safor/index.html
> +        <section class="six">
Change names of sections to be more descriptive, for example: footer-feedback or feedback-form.
Please do this for every section and sub div in the document.

2019-06-29 14:25 UTC, volo-maslow approved these changes

2019-06-29 14:26 UTC, ghost approved these changes

2019-06-29 14:27 UTC, merged