Initial commit
futuro-camp/education-group-one pull request #6
Opened 2019-06-24 14:06 UTC by l-koliesnik

2019-06-24 19:31 UTC, ghost requested changes
Adaptive is not implemented for 1024px and less

2019-06-24 19:31 UTC, ghost commented on index.html
> +                <h1>SAFOR<br>
Please don't use `<br>`

2019-06-24 19:31 UTC, ghost commented on index.html
> +            <h2>Reliability</h2>
There better use list for containing items

2019-06-24 19:31 UTC, ghost commented on index.html
> +        <div id="fivetext">
Use list for this too

2019-06-25 14:14 UTC, ghost requested changes

2019-06-25 14:14 UTC, muha2399 commented on index.html
> +    <div class="footer-tablet">
Please don't create tablet version of divs, do not repeat code, just style previous one with css.

2019-06-25 14:14 UTC, muha2399 commented on index.html
> +    <div class="fivefortablet">
Why do we need version for tablet ? It can be changed using css.

2019-06-29 13:42 UTC, muha2399 commented on index.html
> +                <h1>SAFOR<br>
Still reproduces in some lines of code

2019-06-29 13:49 UTC, volo-maslow requested changes

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +
The spacing here is useless, please remove all newlines between elements.

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +    <link href="./assets/style.css" type="text/css" rel="stylesheet">
Do not use ./ to reference a file (styles or js), just use the folder name or file itself. (assets/style.css).
Change for all href's.

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +                <h1>switching your<br>
Please remove all BR's, this should be working with single text inside without any inner tags.

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +    <div class="two">
Change class names to be more descriptive, for example - main-content, or footer-feedback, or anything else representing the content inside the div or section.

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +    <div class="one">
Please use section instead of div's here, top-level divs should be a section.

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +                    <h3 id="abouth3"><a href=" ">WATCH NOW</a></h3>
Please use underscore or dash to separate two different tags. Same for all Id's and Classes in document.

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +                <br><br>
Do not use `<br>` inside the text, it is not possible to update such field from admin panel, users will not enter a `<br>` tag inside their text, they will have just a raw text instead.

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +        <div class="forbusiness" id="forbusiness">
ID here is useless, please use only a class. Also please review the document, a lot of parts doesn't seem to be needed (especially a combo with id & class with the same name).

2019-06-29 13:49 UTC, volo-maslow commented on index.html
> +            <h2>Reliability</h2>
This should be done with UL & LI elements.

2020-10-02 21:12 UTC, closed without merging